version: '2'
services:
  redis:
    build: ./redis
    ports:
     - "6379:6379"
    volumes:
     - ./redis:/opt/redis
  api:
    build: ./api
    ports:
     - "8088:8088"
    volumes:
     - ./api:/code
    depends_on:
     - redis
    links:
     - redis
